CREATE TABLE ALUNO_DISCIPLINA (
	codigo_disciplina CHAR(6) NOT NULL REFERENCES DISCIPLINA(codigo_disciplina) ON DELETE CASCADE,
    ra CHAR(13) NOT NULL REFERENCES ALUNO(ra) ON DELETE CASCADE,
    PRIMARY KEY (codigo_disciplina, ra)
);
